### ISSUE TITLE
CraftQL performance

### ISSUE THREAD

**Issue by pauloelias** [markhuot/craftql#220]
Apologies if this issue is related of #150 and/or #166 so let me know if I should add to one or both of those threads.

We're running into pretty long response times when trying to run queries -- either from the frontend, gatsby builds, or in graphiql -- and we are not sure why.

For example, the following query is taking 4+ seconds and we are at a loss as to why this might be happening in our staging environment (that mirrors our production environment when we go live).

```
{
  entry(id: 52187) {
    ... on Blog {
      thumbnail {
        url
      }
    }
  }
}
```

Locally queries are a tad faster in our Docker setup but they still take longer than than they do if pulling the same data out into a template.

Are there any known performance issues that are not outlined in the docs that can help us reduce the response times of some our queries before we go down the road of adding a caching layer in front of our graphql endpoint (which is a whole can of worms)?

Server: Heroku Standard-2x-Dyno (1Gb ram)
PHP: 7.2.14
Postgres: 10.6 (Heroku Postres Standard 0)
Craft 3.0.40
CraftQL: dev-master 3a8329b

@timkelty are you still running your branch on production? Has your fork been updated with any of the latest CraftQL updates?

Huge thanks for any pointers you can send our way!

**Comment by khalwat** [comment]
@markhuot it'd make profiling things super nice if you stuck in some profiling code around bottlenecks ala:

https://nystudio107.com/blog/profiling-your-website-with-craft-cms-3s-debug-toolbar#plugin-developers

```
Craft::beginProfile('someUniqueIdentifier', __METHOD__);
// Insert code here
Craft::endProfile('someUniqueIdentifier', __METHOD__);
```

**Comment by timkelty** [comment]
@pauloelias Indeed I am still running my branch in production, unfortunately.

Here's my changes: https://github.com/markhuot/craftql/compare/master...timkelty:dlr2018

I kept it up to date with changes for a while, but haven't recently.
I did just try to rebase my branch off markhuot/master and it rebased with no conflicts, but I haven't tested it. Here's everything the between current master and when I last updated my branch: https://github.com/timkelty/craftql/compare/dlr2018...markhuot:master

From my experience, you long load times likely are not the result of the specific query, but in the size/complexity of your Craft installation (namely fields/field layouts). As the amount of fields increase, the GQL schema build time increases, which has to happen EVERY request.

The difficulty lies in the fact that the schema contains closures, and therefore is not easily cacheable.

To get around this, my branch caches _the entire response_. It is by no means a good solution, but is my only option at the moment.

**Comment by pauloelias** [comment]
@timkelty Thank you for your response!

The scheme regeneration on each request sounds like the issue we are dealing with so I will chat with you in slack about it.

**Comment by markhuot** [comment]
This has been a rather interesting and troubling issue to work on. However, I can tell you all a few things,

1. when you're pulling _a lot_ of data it's slow because Craft has to make model objects for everything. Creating all those `Entry` elements takes time. I don't have a great way to fix this but keeping your limits `< 100` definitely helps.
2. as @timkelty mentions the more complex your Craft build the longer it takes GraphQL to build the schema. I've been doing a good amount of research on this and there are ways to work around the "PHP caching closures" issue. However, an even better approach is to have the schema lazy load, which I'm working on. Currently if you're requesting `{ entries { id } }` it's going to also instantiate _every_ single Volume object, Matrix object, Section object and Entry Type Object even though they're not needed. I'm very close to pushing a branch that removes those unneeded objects lazy loads only what is needed. In my testing it took a pull of 700+ entries from 30 seconds down to 4 seconds. For more realistic pulls of 100 entries it went from 5 seconds down to 800ms.

I'm continuing to see what else can be done to improve speeds, but hopefully this lazy schema update should help!

I'm attaching a flame graph of the before and after so you can see the improvements in a visual fashion as well (also because I _love_ me some flame graphs). The left is before and the right is the after. The most notable updates are called out in colored boxes,

- orange shows the schema generation has been shortened from 18 seconds to around 1 second
- green shows the actual `craft.entries` query takes approximately the same 7-8 seconds
- red shows the actual loop over the query results turning the results in to GraphQL objects which takes around the same 5 seconds. The big difference is how much less dense that area is because I've reduced redundant DB queries and extraneous `$entry->section->handle` lookups that would continuously hit the DB asking for the Section just to get the handle.

![screen shot 2019-02-04 at 4 05 12 pm](https://user-images.githubusercontent.com/48975/52237422-78995c00-2897-11e9-8fc3-21fcb9d4ba46.png)

Anyway, I'll keep you all updated as I progress. The work is currently on the `builder-refactor3` branch but it's not even close to stable yet so I wouldn't use it yet.

Regarding a few specific points,

> Are there any known performance issues that are not outlined in the docs that can help us reduce the response times of some our queries before we go down the road of adding a caching layer in front of our graphql endpoint (which is a whole can of worms)?

Complex schemas are the worst offender. Also running `debugMode` adds a `validateSchema` call which _definitely_ slows things down. If speeds are painful I'd try disabling `debugMode` and see if it helps.

> it'd make profiling things super nice if you stuck in some profiling code around bottlenecks ala:

Agreed. However, when I put those in I saw my times increase from a second to four seconds. The profiling really seems to slow things down.

> To get around this, my branch caches the entire response. It is by no means a good solution, but is my only option at the moment.

Yup, after I get this lazy loading in place I'd like to get Apollo Engine supported so we can use their per-key caching layers.

**Comment by timkelty** [comment]
> Yup, after I get this lazy loading in place I'd like to get Apollo Engine supported so we can use their per-key caching layers.

🥇

**Comment by pauloelias** [comment]
Thanks all!

I am really excited to see where this plugin is heading. Top notch work all around!

**Comment by narration-sd** [comment]
Indeed it's good to hear the progress and directions on this, Mark, Tim, et al. Thanks, as it will make CraftQL as something many want to use.

**Comment by markhuot** [comment]
The 2.x branch is pushed with some significant performance improvements. Typically I'm seeing sill expensive queries go from 30s down to 1s. You can test it with,

```
composer require markhuot/craftql ~2@beta
```

This should have feature parity with the 1.x versions but I haven't confirmed _everything_ yet so don't go run and enable this in production or anything.

**Comment by pauloelias** [comment]
@markhuot this is AMAZING!

Thank you so much for getting this pushed up. We'll try it out and report back.

**Comment by pauloelias** [comment]
@markhuot is there a trick to updating to this beta from `dev-master`? I was able to install on 3.0.40 so it doesn't look like 3.1 is a requirement.

The graphql endpoint errors out with a 404 when I hit from the frontend or curl.

I did the following after the update:

- Double checked my user permissions
- API endpoint setting
- Tried running the test `curl` command
- Error displayed in graphiql: `"error": "Unable to verify your data submission."`
- Schema does not load in the "Schema docs" with a `No Schema Available` message

```
yii\web\NotFoundHttpException: Template not found: api in /usr/share/nginx/vendor/craftcms/cms/src/controllers/TemplatesController.php:70
Stack trace:
#0 [internal function]: craft\controllers\TemplatesController->actionRender('api', Array)
#1 /usr/share/nginx/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /usr/share/nginx/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /usr/share/nginx/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('render', Array)
#4 /usr/share/nginx/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#5 /usr/share/nginx/vendor/craftcms/cms/src/web/Application.php(284): yii\base\Module->runAction('templates/rende...', Array)
#6 /usr/share/nginx/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#7 /usr/share/nginx/vendor/craftcms/cms/src/web/Application.php(273): yii\web\Application->handleRequest(Object(craft\web\Request))
#8 /usr/share/nginx/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /usr/share/nginx/web/index.php(21): yii\base\Application->run()
#10 {main}```

**Comment by markhuot** [comment]
No trick, that I'm aware of ;). It should work on 3.0 or 3.1. Although, let me confirm that… (more in a bit).

The updates were to the schema generation so the routing and `/api` endpoint should remain unchanged.

**Comment by markhuot** [comment]
Okay, yea, 3.0.40 and the latest 3.1 both work okay with `~2@beta` for me.

<img width="1532" alt="screen shot 2019-02-06 at 2 05 14 pm" src="https://user-images.githubusercontent.com/48975/52366653-482cfb80-2a18-11e9-893b-cf01df5ed07f.png">

Regarding the error, `"error": "Unable to verify your data submission."`. That comes from Yii's CSRF protection, which is disabled for the API endpoint. Based on CSRF running, the 404 on `/api`, and the "No Schema Available" it really feels like the plugin isn't installed any more. For my own sanity can you try uninstalling it and re-installing it? You'll lose your tokens though so only do this as a test and don't do it in production unless you're okay with generating new tokens.

**Comment by pauloelias** [comment]
@markhuot I've been trying that...

- Uninstall from the CP then reinstall
- Uninstall from the CP, remove from composer.json file,remove `vendor` dir, and then reinstall via composer

I just reverted to `dev-master` just to make sure I am not going crazy but here's a weird catch:

- I can hit the endpoint via curl without a problem
- I get the same error and the schema won't load either

my `siteUrl` is set to `null` but that wasn't an issue before.

Other things I am doing:

- logging in and out of the site
- Clearing cookies and site data for the domain
- Clearing cache via the `craft' CLI and the web interface

I am about to restart my damn computer to see if that works :P

**Comment by markhuot** [comment]
_Very_ odd. The 2.x branch shouldn't have altered anything (config or database-wise) so going back and forth between the two branches should be possible.

Let me know what I can do to help here. If you're able to—feel free to email me a database export and I'll try to recreate it locally.

**Comment by pauloelias** [comment]
Before I bother you offline I decided to try and see if I could get this working remotely in our staging instance to make sure my local docker setup isn't all wonky.

With 2.0.0.beta.1 I am able to hit the endpoint using the `helloWorld` query. When I try to use graphiql in the browser, though, the schema doesn't load and I get the following error:

```
TypeError: Cannot read property 'types' of undefined
    at buildClientSchema (https://XXXXX.herokuapp.com/cpresources/a6a16/ajax/libs/graphiql/0.11.10/graphiql.js?v=1549488114:31008:72)
    at https://XXXXX.herokuapp.com/cpresources/a6a16/ajax/libs/graphiql/0.11.10/graphiql.js?v=1549488114:2190:55
```

I clear caches and run migrations on deploy so `cpresources` should be empty before I hit the CP. The remote server does not have `devMode` enabled and that is the only real config difference between my local setup and the remote instance.

Of course, downgrading to 1.1.3 works fine 🤷‍♂️

**Comment by markhuot** [comment]
That `graphiql` resource shouldn't have updated with the 2.0.0 beta so I wouldn't worry about that.

"Cannot read property 'types' of undefined" sounds like the GraphiQL introspection query isn't returning anything/everything. This feels like the 2.0.0 update is failing on your schema for some reason. If you can share a database that would be ideal. If not, could you try running the following and seeing if it will generate a schema file?

```
./craft craftql/tools/print-schema > /path/to/some/file.graphql
```

**Comment by narration-sd** [comment]
If it's useful here, I've run back and forth between dev-master and ~2@beta several times just now, with results:
- 2@beta works fine run inside Craft via the service
- it also runs fine called externally on its Craft api via gatsby build
- performance gain looks like 14queries/sec vs 11, according to gatsby build logging
- times for gatsby access look rational for query rate
- CraftiQL feels a bit snappier, as do my Live Vue CP editing updates on the Gatsby site
- the entries portion of schema is very simple for this case - just a body and an image

This is running all parts on an i7 laptop, Chrome Canary w/nginx serving Gatsby and Craft/GrafQL on a Vagrant vm, Win10 latest underneath. Timings taken with devMode false.

**Comment by narration-sd** [comment]
^updated to add result on full schema query

**Comment by pauloelias** [comment]
Thank you so much for taking your time to help me out with this. I REALLY appreciate it!

Running `./craft craftql/tools/print-schema > schema.graphql` inside my local docker container:

```
root@752b70d4043c:/usr/share/nginx# ./craft craftql/tools/print-schema > schema.graphql
Exception 'GraphQL\Error\InvariantViolation' with message 'Each entry of schema types must be instance of GraphQL\Type\Definition\Type but entry at 44 is false'

in /usr/share/nginx/vendor/webonyx/graphql-php/src/Type/Schema.php:254

Stack trace:
#0 /usr/share/nginx/vendor/webonyx/graphql-php/src/Type/Schema.php(227): GraphQL\Type\Schema->resolveAdditionalTypes()
#1 /usr/share/nginx/vendor/webonyx/graphql-php/src/Type/Schema.php(195): GraphQL\Type\Schema->collectAllTypes()
#2 /usr/share/nginx/vendor/webonyx/graphql-php/src/Type/Schema.php(418): GraphQL\Type\Schema->getTypeMap()
#3 /usr/share/nginx/vendor/markhuot/craftql/src/Services/GraphQLService.php(183): GraphQL\Type\Schema->assertValid()
#4 /usr/share/nginx/vendor/markhuot/craftql/src/Console/ToolsController.php(572): markhuot\CraftQL\Services\GraphQLService->getSchema(Object(markhuot\CraftQL\Models\Token))
#5 [internal function]: markhuot\CraftQL\Console\ToolsController->actionPrintSchema()
#6 /usr/share/nginx/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /usr/share/nginx/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 /usr/share/nginx/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('print-schema', Array)
#9 /usr/share/nginx/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('print-schema', Array)
#10 /usr/share/nginx/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('craftql/tools/p...', Array)
#11 /usr/share/nginx/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('craftql/tools/p...', Array)
#12 /usr/share/nginx/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#13 /usr/share/nginx/craft(22): yii\base\Application->run()
#14 {main}
```

Running `./craft craftql/tools/print-schema > schema.graphql` inside a Heroku dyno works fine though 🤷‍♂️

I'll shoot over the DB because something seems super wonky.

**Comment by pauloelias** [comment]
I was able to get 1.3.1 working locally by specifying a `siteUrl` (used to be `null` which worked fine until recently):

```
'siteUrl' => 'http://localhost'
```

2.0 beta is still not working for some reason. When trying to use the beta I am noticing this in browser's console:

1. Unless I am misreading this the Authorization header doesn't seem to set token:

```
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7
Authorization: Bearer
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 1550
Content-Type: application/json
Cookie: 1031b8c41dfff97a311a7ac99863bdc5_username=fc06311a99ef5df805075748d2d1728f36f6fc3dc3523c956e52576dc47b803fa%3A2%3A%7Bi%3A0%3Bs%3A41%3A%221031b8c41dfff97a311a7ac99863bdc5_username%22%3Bi%3A1%3Bs%3A14%3A%22paulo%40ideo.com%22%3B%7D; PHPSESSID=b6o133o7nfb7vgfluaa3ds4kij; 1031b8c41dfff97a311a7ac99863bdc5_identity=8329857fca203a31a477d50116a094c0c3df43b7c74c989c450901d3c1259dbca%3A2%3A%7Bi%3A0%3Bs%3A41%3A%221031b8c41dfff97a311a7ac99863bdc5_identity%22%3Bi%3A1%3Bs%3A288%3A%22%5B2%2C%22%5B%5C%22dhX8l1rWalXsOacpvoUKFwUNUKnMtxRLbTNDrvguLqxNMJvzI8VgM1ENpLnmvm7bpxBXf7c_ysyY_Ee_-5Jfy2p2ALBMuwqOvfS5%5C%22%2C%5C%228d8fa0ae-239d-4f2a-87ac-e0d05dfe03f2%5C%22%2C%5C%22Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_13_6%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F74.0.3694.0+Safari%2F537.36%5C%22%5D%22%2C3187209600%5D%22%3B%7D; CRAFT_CSRF_TOKEN=88f8358120f9611e100832449cf549d11065ff8b5a3d3ad70140ca915f5fcb4fa%3A2%3A%7Bi%3A0%3Bs%3A16%3A%22CRAFT_CSRF_TOKEN%22%3Bi%3A1%3Bs%3A208%3A%22o4WWJBLjawY1GNgnriMpWl6DWoucHb7mfBGndJgI%7C65f2a8c9cb5faccb99e72a50492895b112e0ebf17b3b3880aa52c08245a24286o4WWJBLjawY1GNgnriMpWl6DWoucHb7mfBGndJgI%7C2%7C%242y%2413%24lBxP5zeX6GDQOBsxZvH3WOIeMumq8VJo00lw9Yno84aa4UdNm%2FiYy%22%3B%7D
DNT: 1
Host: localhost
Origin: http://localhost
Pragma: no-cache
Referer: http://localhost/cp/craftql/browse
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Safari/537.36
```

![screenshot 2019-02-06 22 53 26](https://user-images.githubusercontent.com/978535/52395254-4425cb80-2a62-11e9-845a-91396875dd92.png)

browse:485 points to this:

```js
    function graphQLFetcher(graphQLParams) {
        // This example expects a GraphQL server at the path /graphql.
        // Change this to point wherever you host your GraphQL server.
        return fetch('http://localhost/api', {
          method: 'post',
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ',
          },
          body: JSON.stringify(graphQLParams),
          credentials: 'include',
        }).then(function (response) {
          return response.text();
        }).then(function (responseBody) {
          try {
            return JSON.parse(responseBody);
          } catch (error) {
            return responseBody;
          }
        });
      }
```

I'm assuming the 500 server error has something to do with not being able to run `./craft craftql/tools/print-schema > schema.graphql` in my docker container:

```sh
root@6aed303eb0cc:/usr/share/nginx# ./craft craftql/tools/print-schema > schema.graphql
Exception 'GraphQL\Error\InvariantViolation' with message 'Each entry of schema types must be instance of GraphQL\Type\Definition\Type but entry at 44 is false'

in /usr/share/nginx/vendor/webonyx/graphql-php/src/Type/Schema.php:254

Stack trace:
#0 /usr/share/nginx/vendor/webonyx/graphql-php/src/Type/Schema.php(227): GraphQL\Type\Schema->resolveAdditionalTypes()
#1 /usr/share/nginx/vendor/webonyx/graphql-php/src/Type/Schema.php(195): GraphQL\Type\Schema->collectAllTypes()
#2 /usr/share/nginx/vendor/webonyx/graphql-php/src/Type/Schema.php(418): GraphQL\Type\Schema->getTypeMap()
#3 /usr/share/nginx/vendor/markhuot/craftql/src/Services/GraphQLService.php(183): GraphQL\Type\Schema->assertValid()
#4 /usr/share/nginx/vendor/markhuot/craftql/src/Console/ToolsController.php(572): markhuot\CraftQL\Services\GraphQLService->getSchema(Object(markhuot\CraftQL\Models\Token))
#5 [internal function]: markhuot\CraftQL\Console\ToolsController->actionPrintSchema()
#6 /usr/share/nginx/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /usr/share/nginx/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 /usr/share/nginx/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('print-schema', Array)
#9 /usr/share/nginx/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('print-schema', Array)
#10 /usr/share/nginx/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('craftql/tools/p...', Array)
#11 /usr/share/nginx/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('craftql/tools/p...', Array)
#12 /usr/share/nginx/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#13 /usr/share/nginx/craft(22): yii\base\Application->run()
#14 {main}
```

**Comment by timkelty** [comment]
@pauloelias my setup is dockerized too, so I'll try this today and see what I get

**Comment by timkelty** [comment]
Hmmm for me on `3.0.40` on `markhuot/craftql@2.0.0-beta1` I'm getting:

```
Exception 'GraphQL\Error\InvariantViolation' with message 'Each entry of schema types must be instance of GraphQL\Type\Definition\Type but entry at 55 is false'
```

**Comment by markhuot** [comment]
Ah, so the issue has to do with how the Tag Group object types are created. I'm working on a fix for this now. Thanks for bearing with me everyone.

**Comment by narration-sd** [comment]
When you guys get done, I would sincerely like to hear how this problem relates to running in a container.

Tight work, anyway, by all concerned. And for your black humor/fellow-feeling side, it happens that Wells Fargo Bank has lost just  about their entire  customer-facing IT, for all of today so far.

Without any evidence, I will blame containers; containers R fun...

**Comment by pauloelias** [comment]
@markhuot thank you again!

@timkelty yup, it has to be our tags/tag groups

@narration-sd turns out it's a DB issue, not a container issue. I made a mistake and though 2.0beta was working when it was deployed to Heroku but it ended up flagging the same error when I tried to generate the schema. To much time staring at the darn screen.

**Comment by narration-sd** [comment]
@pauloelias definitely can identify with the screen-staring ;) and glad this is on road to being sorted.

Wells Fargo’s ‘container’ turned out to be a server building that burned down. They’ve got all operating again, if working slowly. A bit of a surprise there wasn‘t full failover geographic diversity, but then, AT&T, if you remember that one.

Thanks for the note on cause, and take care

**Comment by timkelty** [comment]
@pauloelias if you're still considering using my branch to get you by in the interim, I rebased it off markhuot/master. Nothing appears to have conflicted or broken:

https://github.com/timkelty/craftql/tree/response-caching

**Comment by markhuot** [comment]
Okay, the `2.x-dev` branch should include fixes for the tags problem. @pauloelias, you should be able to run `2.x-dev` against your schema now without issue. I'm still trying to optimize it further but you should see improvements from 5s down to 1.2s.

**Comment by narration-sd** [comment]
@markhuot  2.x-dev runs fine here.  Not seeing any performance change, still circa 14 queries/sec on this testbed for quite other things, with its minimal number of sections and entries to be schema'd and queried.

Quite possibly the optimizing  you mention is for other things, even the tags, but thought you'd like to see some reply as early as possible...cheers on all the work!

**Comment by pauloelias** [comment]
@markhuot `2.x-dev` seems to be running beautifully, thank you so much!

We'll do more testing over the next few days and report back if we see anything amiss.

@timkelty thank you sir! I really appreciate your help too.

**Comment by markhuot** [comment]
That's great news @pauloelias, I'm curious if you see any performance improvements too.

Note: the biggest wins will be pulling 10 (or 100) entries of a single (or limited) content types. If you're pulling 100 entries spread across _all_ content types then the improvements will be minimal because either way GraphQL has to instantiate all those types.

**Comment by narration-sd** [comment]
@markhuot yes, I thought that would be best area of perf gain, but felt also it was good to give some feedback along with lights-are-still-on notice during the fix-find-trail this issue conversation turned to.

I'm still seeing that 30-40% improvement even so, in this constrained situation, and every bit helps -- just ask @khalwat....

**Comment by pauloelias** [comment]
@markhuot after giving this branch a go for a bit we've found a few things that might be bugs because they were working with our original queries:

1. Using the `site` filter on queries creates an internal server error. It’s possible to still select the right site by using the `siteId` filter though.

This returns a 503 error:

```
{
  entry: entry(type: Blog, slug: "our-top-10-stories-of-2018", site: en) {
    ... on Blog {
      slug
      title
    }
  }
}
```

This query returns `Argument \"site\" has invalid value \"en\".\nExpected type \"SitesEnum\", found \"en\".`
```
{
  entry: entry(type: Blog, slug: "our-top-10-stories-of-2018", site: "en") {
    ... on Blog {
      slug
      title
    }
  }
}
```

2. Slugs are now of type [String] (array of strings) instead of String, is this correct?

3. Our InlineContentImageBlock (and many other types) have lost all their fields in the schema, see:

![image](https://user-images.githubusercontent.com/978535/53040780-1a43b000-3437-11e9-8d37-1f692498caa1.png)

Despite of these few items the performance is **noticeably** faster. Thank you!

**Comment by seidtgeist** [comment]
For our project, @pauloelias and I have downgraded the plugin back to a version with the previous schema and put a tiny custom caching node proxy in front of it. It normalizes queries, hashes them for a cache key and stores responses in a redis instance. For our gatsby use-case this gets us from less than <1 to 35+ queries per second, which is likely a limit on the gatsby side.

Looking forward to using the 2.x-dev branch again though, and very happy to share data and help!

**Comment by markhuot** [comment]
@pauloelias and @seidtgeist, your issues on the `2.x` branch should be (mostly) resolved now. The missing fields should be back.

A few notes on 2.x,

1. Yes, `site:` is now an Enum instead of a string. This is a breaking change so I want to make it now. The reason behind the change is that since Type and Section are enums it makes sense that Site would be an enum too.
2. Slugs are of type `[String]` now but thanks to GraphQL you can pass in `slug: "foo"` and GraphQL will automatically convert that to `slug: ["foo"]` before sending it on to the resolvers. This _should not_ be a breaking change since the old syntax will still work. You should have the added benefit of passing multiple slugs to queries now, just like you can with `craft.entries` in Twig.

Note: I finally re-worked Travis on this so that each push checks a control schema print against the current schema print. This should ensure no types go missing as a result, phew, https://travis-ci.org/markhuot/craftql/builds/497276490

I'm preparing this for a release in the next few weeks. If anyone has any time/inclination to test the `2.x-dev` version I'd appreciate it. Thank you!

**Comment by pauloelias** [comment]
@markhuot Great news all around!

We'll give it a go and report back any issues we come across.

**Comment by markhuot** [comment]
FYI, I made further updates to the `2.x` branch that should help _all_ schemas, not just complex schemas. The optimization avoids spinning up unnecessary types so a query for entry types doesn't even touch the Globals, Volumes, Categories, or Tags types. Because of that I'm seeing improvements on a sample schema from 5s down to 800ms or so.

**Comment by seidtgeist** [comment]
@markhuot Thank you so much, we really appreciate your hard work! Will report back later today or tomorrow on our findings with the latest API 🤘

**Comment by pauloelias** [comment]
@markhuot I just pulled down what I think is the correct branch and I am running into the following errors when loading the CraftQL Graphiql editor:

```json
{
  "error": "Each entry of schema types must be instance of GraphQL\\Type\\Definition\\Type but entry at 6 is false"
}
```

In the console I am seeing this for `https://domain.com/api`:

![image](https://user-images.githubusercontent.com/978535/53460201-2d372100-39f1-11e9-9bd4-c71d256d91ae.png)

Same issues in local development with the same DB.

Local/Remote Dev:
Craft 3.0.41
Postres 10.6
PHP 7.3.2

When you have a moment, can you confirm what we should have listed in our `composer.json` file to make sure we're using the correct branch/commit?

`~2@dev` seems to be correct because `~2@beta` gives is the old schema error we had before:

```json
{
  "error": "Each entry of schema types must be instance of GraphQL\\Type\\Definition\\Type but entry at 44 is false"
}
```

Thanks again and again for all of your help with this!

**Comment by markhuot** [comment]
Thanks @pauloelias, I pushed a fix for this and updated the test cases to catch this in the future.

----

Additionally, for complex schemas such as yours, I would highly recommend disabling Schema Validation. There are two ways to do this,

1. `'devMode' => false` in your `config/general.php` (this has the unintended consequence of hiding error messages during development)
2. `'disableSchemaValidation' => true` in your `config/craftql.php` (this _only_ affects CraftQL schema validation and will allow you to leave `devMode` enabled for other work)

**Comment by pauloelias** [comment]
@markhuot we're back in business, thank you so much!

**Comment by pauloelias** [comment]
@markhuot so far the only issue that we are running into is we can't seem to query by "site":

```
{
  entry(site: en, slug: "thoughtless-acts-monsoon-season") {
    ... on Blog {
      thumbnail {
        url
      }
    }
  }
}
```

The above query returns this error:
```
{
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "entry"
      ]
    }
  ],
  "data": {
    "entry": null
  }
}
```

**Comment by markhuot** [comment]
That should be fixed up now, thanks so much for testing this out. I'm _really_ liking where the code base is for this new branch. It's a _huge_ improvement over my first pass at all this. Things are _much_ cleaner.

Last step before merging this is checking over all the token scopes. I think some of the scopes got lost in the refactoring so I'll confirm all that and then prep this for merging to `dev-master`. I'm hoping that'll be some time next week-ish.

**Comment by pauloelias** [comment]
@markhuot sorry for taking so long to get to you on this. On a new branch I blew out my vendor folder and tried installing craft with `~2@dev` again.

I am not seeing any console errors but I am getting this in graphiql in the Craft CMS admin area:

```
Error: Must be named. Unexpected name: .
    at assertValidName (http://localhost/cpresources/35b3c05a/ajax/libs/graphiql/0.11.10/graphiql.js?v=1552432422:30287:11)
    at http://localhost/cpresources/35b3c05a/ajax/libs/graphiql/0.11.10/graphiql.js?v=1552432422:28280:42
    at Array.forEach (<anonymous>)
    at defineFieldMap (http://localhost/cpresources/35b3c05a/ajax/libs/graphiql/0.11.10/graphiql.js?v=1552432422:28279:14)
    at GraphQLObjectType.getFields (http://localhost/cpresources/35b3c05a/ajax/libs/graphiql/0.11.10/graphiql.js?v=1552432422:28233:44)
    at typeMapReducer (http://localhost/cpresources/35b3c05a/ajax/libs/graphiql/0.11.10/graphiql.js?v=1552432422:29950:25)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (http://localhost/cpresources/35b3c05a/ajax/libs/graphiql/0.11.10/graphiql.js?v=1552432422:29839:34)
    at buildClientSchema (http://localhost/cpresources/35b3c05a/ajax/libs/graphiql/0.11.10/graphiql.js?v=1552432422:31247:10)
    at http://localhost/cpresources/35b3c05a/ajax/libs/graphiql/0.11.10/graphiql.js?v=1552432422:2190:55
```

I cleared out the `cpresources` directory, browser cache, and even tried using an incognito window but I can't seem to shake the above error in graphiql in the Craft admin.

I can, however, use the desktop graphiql app to run queries. When running some test queries in graphiql with`~2@dev`, it doesn't seem to return all of our "sites" so we can't query by site.

For example it is only returning our China site/locale but not any of the other three in the autocomplete or generated documentation:

![image](https://user-images.githubusercontent.com/978535/54242929-b10a0680-44e3-11e9-832c-afd5abba0db6.png)

`zh` it not our primary site either.

Let me know if you need any more info and thanks again for being so patient with this!

**Comment by markhuot** [comment]
Thank you! This has been super helpful. I’ll dig in to those issues and get back to you.

**Comment by pauloelias** [comment]
> Thank you! This has been super helpful. I’ll dig in to those issues and get back to you.

Hey @markhuot,

Have you had a chance to look into the `Error: Must be named. Unexpected name: .` error references in my [previous comment](https://github.com/markhuot/craftql/issues/220#issuecomment-472220532)?

**Comment by nickroberts** [comment]
I'm having issues when using enums for the site param.

Here is my query:
```graphql
{
  entries(site: siteTwo) {
    id
    title
  }
}
```
Here is the response:
```json
{
  "error": "Invalid site handle: 2"
}
```
I can query by `siteId` and it works as expected.

I also tried blowing away the vendor folder, but I'm still getting this error.

**Comment by tinchalamo** [comment]
@pauloelias how did you get rid of the "Unable to verify your data submission." error? I'm on a fresh install of Craft 3.1.28 with CraftQL 1.3.2 and cannot get past this error.

**Comment by pauloelias** [comment]
@tinchalamo if I remember correctly I had to blow out the `cpresources` cache or enable the proper read permissions in the app

**Comment by narration-sd** [comment]
@pauloelias Paulo, I'm getting  this "Unable...data submission" also, on an abso fresh install of Craft, w/CraftQL from the Plugin Store, which results in CraftQL 1.3.2. 

rm -r cpresources has no good effect. Site otherwise is fine, and as you found, curl access is fine, as is for the most part remote Gatsby access.

- can you remember anything else you might have done?
- @markhuot, is there something missing in CraftQL 1.3.2 vs. Craft 3.1.30 which results in this problem?

I'm having no trouble on dev sites using CraftQL 2.x. But I need to veriify others are going to be able to use a plugin about to release, and they're going to get 1.x and fail, it looks like. That's what the present failing test site is about. I need Craftiql to work as there's some other specific schema problem to find.

**Comment by mauricioprado00** [comment]
Problem is that it does not work when the url is set straight from the environment variables. Instead one needs to do this:

'siteUrl' => getenv('DEFAULT_SITE_URL')
